from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
	path('',views.home,name='home'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('doctor_register/',views.doctor_register,name='doctor_register'),
    path('customer_register/',views.customer_register,name='customer_register'),
    path('customer_login/',views.customer_login,name='customer_login'),
	path('customer_appointments/',views.customer_appointments,name='customer_appointments'),
    path('doctor_login/',views.doctor_login,name='doctor_login'),
    path('add_visiting_hour/',views.add_visiting_hour,name='add_visiting_hour'),
    path('view_visiting_hours/',views.view_visiting_hours,name='view_visiting_hours'),
    path('appointment/',views.appointment,name='appointment'),
    path('customer_dashboard/',views.customer_dashboard,name='customer_dashboard'),
    path('search_doctor/',views.search_doctor,name='search_doctor'),
    path('customer_logout/',views.customer_logout,name='customer_logout'),
    path('logout/',views.logout,name='logout'),
    path('book_appointment/',views.appoint,name='appoint'),
    path('update_status/<int:pk>/',views.update_status,name='update_status'),
    path('cancel_app/<int:pk>/',views.cancel_app,name='cancel_app'),
    path('edit_visiting/<int:pk>/',views.edit_visiting,name='edit_visiting'),
    path('delete_visiting/<int:pk>/',views.delete_visiting,name='delete_visiting'),
	path('search_patient/',views.search_patient,name='search_patient'),
	path('add_patient/',views.add_patient,name='add_patient'),
	path('add_report/<int:pk>/<int:pid>/',views.add_report,name='add_report'),
	path('view_report/<int:pk>/',views.view_report,name='view_report'),
	path('patient_report/',views.patient_report,name='patient_report'),
	path('disease_alert/',views.disease_alert,name='disease_alert'),
	path('cdisease_alert/',views.cdisease_alert,name='cdisease_alert'),
	path('chart/',views.chart,name='chart'),
	url(r'^ajax/ajax_disease_spread/$', views.ajax_disease_spread, name='ajax_disease_spread'),
	path('disease_count/',views.disease_count,name='disease_count'),
	path('add_disease/',views.add_disease,name='add_disease'),
	path('disease/',views.disease,name='disease'),
	path('update_disease/<int:pk>/',views.update_disease,name='update_disease'),
	path('delete_disease/<int:pk>/',views.delete_disease,name='delete_disease'),
	path('admin_dashboard/',views.admin_dashboard,name='admin_dashboard'),
	path('admin_disease/',views.admin_disease,name='admin_disease'),
	path('hospital_search/',views.hospital_search,name='hospital_search'),
	path('area_disease/',views.area_disease,name='area_disease'),
	path('area_disease/',views.area_disease,name='area_disease'),
	path('new_disease/',views.new_disease,name='new_disease'),
	path('new/',views.new,name='new'),
	path('admin_new/',views.admin_new,name='admin_new'),
	path('search_state/',views.search_state,name='search_state'),
]

