# Generated by Django 2.2.4 on 2021-03-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('doc_license_no', models.CharField(max_length=30, null=True, unique=True)),
                ('hospital_license_no', models.CharField(max_length=30, null=True, unique=True)),
                ('doc_license_expire_date', models.DateField(max_length=30, null=True)),
                ('hospital_license_expire_date', models.DateField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('hospital_address', models.CharField(max_length=200, null=True)),
                ('doctor_type', models.CharField(choices=[('', 'Select'), ('govt', 'Govt Doctor'), ('pvt', 'Private Doctor')], default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, unique=True)),
                ('doctor_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('doc_license_no', models.CharField(max_length=30, unique=True)),
                ('hospital_license_no', models.CharField(max_length=30, unique=True)),
                ('degree', models.CharField(max_length=30, null=True)),
                ('specialist', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('hospital_address', models.CharField(max_length=200)),
                ('doctor_type', models.CharField(choices=[('', 'Select'), ('govt', 'Govt Doctor'), ('pvt', 'Private Doctor')], default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Online_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='documents/', verbose_name='Image/Video')),
                ('msg', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
                ('prescription', models.FileField(upload_to='documents/', verbose_name='Image')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=30, null=True, unique=True)),
                ('pharmacy_number', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True, unique=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('pharmacy_address', models.CharField(max_length=200, null=True)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
        migrations.CreateModel(
            name='Visiting_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiting_hour_weekdays', models.CharField(max_length=30)),
                ('visiting_hour_weekend', models.CharField(max_length=30)),
                ('visiting_hour_online_weekdays', models.CharField(max_length=30)),
                ('visiting_hour_online_weekend', models.CharField(max_length=30)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
        migrations.CreateModel(
            name='Private_Doctor_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.FloatField()),
                ('status', models.CharField(max_length=200)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
                ('online_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Online_Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy_customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablet_price', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
                ('hospital_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
                ('online_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Online_Appointment')),
                ('pharmacy_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=200)),
                ('visiting_date', models.DateField(max_length=30)),
                ('visiting_time', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
    ]
