# Generated by Django 2.2.4 on 2021-03-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=2000)),
                ('image', models.FileField(upload_to='documents/', verbose_name='Patient Image')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
            ],
        ),
    ]
