# Generated by Django 2.2.4 on 2021-03-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=200)),
                ('report', models.FileField(upload_to='documents/', verbose_name='Report')),
                ('visiting_date', models.DateField()),
                ('follow_up_date', models.DateField()),
                ('prescription', models.FileField(upload_to='documents/', verbose_name='Prescription')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient_Detail')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Detail')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
            ],
        ),
    ]
