# Generated by Django 2.2.4 on 2021-03-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_report_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_detail',
            name='doctor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register'),
        ),
    ]
