# Generated by Django 2.2.4 on 2021-03-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210330_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='pharmacy_customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='pharmacy_customer',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='pharmacy_customer',
            name='online_id',
        ),
        migrations.RemoveField(
            model_name='pharmacy_customer',
            name='pharmacy_id',
        ),
        migrations.RemoveField(
            model_name='private_doctor_payment',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='private_doctor_payment',
            name='hospital_id',
        ),
        migrations.RemoveField(
            model_name='private_doctor_payment',
            name='online_id',
        ),
        migrations.DeleteModel(
            name='Online_Appointment',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.DeleteModel(
            name='Pharmacy_customer',
        ),
        migrations.DeleteModel(
            name='Private_Doctor_Payment',
        ),
    ]
