# Generated by Django 2.2.4 on 2021-03-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210330_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=2000)),
                ('symtoms', models.TextField(max_length=2000)),
                ('speed', models.CharField(max_length=200)),
                ('precautions', models.TextField(max_length=2000)),
                ('image', models.FileField(upload_to='documents/', verbose_name='Image')),
                ('date', models.DateField()),
            ],
        ),
    ]
