# Generated by Django 2.2.4 on 2021-03-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_disease_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_detail',
            name='link',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
