# Generated by Django 2.2.4 on 2021-03-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_disease_detail_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('date', models.DateField()),
                ('disease_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disease_Category')),
            ],
        ),
    ]
