# Generated by Django 2.2.4 on 2021-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_disease_category_disease_spread'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease_spread',
            name='cured_count',
            field=models.IntegerField(null=True, verbose_name='Cured Count'),
        ),
        migrations.AddField(
            model_name='disease_spread',
            name='current_count',
            field=models.IntegerField(null=True, verbose_name='No of Currently Affected Count'),
        ),
        migrations.AlterField(
            model_name='disease_spread',
            name='count',
            field=models.IntegerField(null=True, verbose_name='No of Affected Count'),
        ),
    ]
