# Generated by Django 2.2.4 on 2021-04-05 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_disease_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unauthorised_Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=2000)),
                ('symtoms', models.TextField(max_length=2000)),
                ('precautions', models.TextField(max_length=2000)),
                ('date', models.DateField(default=datetime.datetime(2021, 4, 5, 12, 17, 36, 701462, tzinfo=utc), verbose_name='Posted Date')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
    ]
